# Generated by Django 3.2.9 on 2021-12-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho', models.CharField(max_length=250)),
                ('ten', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mat_khau', models.CharField(max_length=100)),
                ('dien_thoai', models.CharField(max_length=20)),
                ('dia_chi', models.TextField()),
            ],
        ),
    ]
